//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :2.0.50727.5483
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]

// Nom du fichier d'origine :
// Date de génération : 26/01/2017 18:11:39
namespace WindowsFormsApplication1
{
    
    /// <summary>
    /// Il n'existe aucun commentaire pour Entities dans le schéma.
    /// </summary>
    public partial class Entities : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initialise un nouvel objet Entities à l'aide de la chaîne de connexion trouvée dans la section « Entities » du fichier de configuration d'application.
        /// </summary>
        public Entities() : 
                base("name=Entities", "Entities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialise un nouvel objet Entities.
        /// </summary>
        public Entities(string connectionString) : 
                base(connectionString, "Entities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialise un nouvel objet Entities.
        /// </summary>
        public Entities(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "Entities")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// Il n'existe aucun commentaire pour Bien dans le schéma.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Bien> Bien
        {
            get
            {
                if ((this._Bien == null))
                {
                    this._Bien = base.CreateQuery<Bien>("[Bien]");
                }
                return this._Bien;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Bien> _Bien;
        /// <summary>
        /// Il n'existe aucun commentaire pour Commande dans le schéma.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Commande> Commande
        {
            get
            {
                if ((this._Commande == null))
                {
                    this._Commande = base.CreateQuery<Commande>("[Commande]");
                }
                return this._Commande;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Commande> _Commande;
        /// <summary>
        /// Il n'existe aucun commentaire pour Pays dans le schéma.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Pays> Pays
        {
            get
            {
                if ((this._Pays == null))
                {
                    this._Pays = base.CreateQuery<Pays>("[Pays]");
                }
                return this._Pays;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Pays> _Pays;
        /// <summary>
        /// Il n'existe aucun commentaire pour Personne dans le schéma.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Personne> Personne
        {
            get
            {
                if ((this._Personne == null))
                {
                    this._Personne = base.CreateQuery<Personne>("[Personne]");
                }
                return this._Personne;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Personne> _Personne;
        /// <summary>
        /// Il n'existe aucun commentaire pour sysdiagrams dans le schéma.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<sysdiagrams> sysdiagrams
        {
            get
            {
                if ((this._sysdiagrams == null))
                {
                    this._sysdiagrams = base.CreateQuery<sysdiagrams>("[sysdiagrams]");
                }
                return this._sysdiagrams;
            }
        }
        private global::System.Data.Objects.ObjectQuery<sysdiagrams> _sysdiagrams;
        /// <summary>
        /// Il n'existe aucun commentaire pour Bien dans le schéma.
        /// </summary>
        public void AddToBien(Bien bien)
        {
            base.AddObject("Bien", bien);
        }
        /// <summary>
        /// Il n'existe aucun commentaire pour Commande dans le schéma.
        /// </summary>
        public void AddToCommande(Commande commande)
        {
            base.AddObject("Commande", commande);
        }
        /// <summary>
        /// Il n'existe aucun commentaire pour Pays dans le schéma.
        /// </summary>
        public void AddToPays(Pays pays)
        {
            base.AddObject("Pays", pays);
        }
        /// <summary>
        /// Il n'existe aucun commentaire pour Personne dans le schéma.
        /// </summary>
        public void AddToPersonne(Personne personne)
        {
            base.AddObject("Personne", personne);
        }
        /// <summary>
        /// Il n'existe aucun commentaire pour sysdiagrams dans le schéma.
        /// </summary>
        public void AddTosysdiagrams(sysdiagrams sysdiagrams)
        {
            base.AddObject("sysdiagrams", sysdiagrams);
        }
    }
    /// <summary>
    /// Il n'existe aucun commentaire pour Model.Bien dans le schéma.
    /// </summary>
    /// <KeyProperties>
    /// id_bien
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="Model", Name="Bien")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Bien : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Créez un nouvel objet Bien.
        /// </summary>
        /// <param name="id_bien">Valeur initiale de id_bien.</param>
        /// <param name="type">Valeur initiale de type.</param>
        public static Bien CreateBien(int id_bien, string type)
        {
            Bien bien = new Bien();
            bien.id_bien = id_bien;
            bien.type = type;
            return bien;
        }
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété id_bien dans le schéma.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int id_bien
        {
            get
            {
                return this._id_bien;
            }
            set
            {
                this.Onid_bienChanging(value);
                this.ReportPropertyChanging("id_bien");
                this._id_bien = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("id_bien");
                this.Onid_bienChanged();
            }
        }
        private int _id_bien;
        partial void Onid_bienChanging(int value);
        partial void Onid_bienChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété type dans le schéma.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string type
        {
            get
            {
                return this._type;
            }
            set
            {
                this.OntypeChanging(value);
                this.ReportPropertyChanging("type");
                this._type = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("type");
                this.OntypeChanged();
            }
        }
        private string _type;
        partial void OntypeChanging(string value);
        partial void OntypeChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété commentaire dans le schéma.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string commentaire
        {
            get
            {
                return this._commentaire;
            }
            set
            {
                this.OncommentaireChanging(value);
                this.ReportPropertyChanging("commentaire");
                this._commentaire = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("commentaire");
                this.OncommentaireChanged();
            }
        }
        private string _commentaire;
        partial void OncommentaireChanging(string value);
        partial void OncommentaireChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété d_cre dans le schéma.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<global::System.DateTime> d_cre
        {
            get
            {
                return this._d_cre;
            }
            set
            {
                this.Ond_creChanging(value);
                this.ReportPropertyChanging("d_cre");
                this._d_cre = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("d_cre");
                this.Ond_creChanged();
            }
        }
        private global::System.Nullable<global::System.DateTime> _d_cre;
        partial void Ond_creChanging(global::System.Nullable<global::System.DateTime> value);
        partial void Ond_creChanged();
    }
    /// <summary>
    /// Il n'existe aucun commentaire pour Model.Commande dans le schéma.
    /// </summary>
    /// <KeyProperties>
    /// id_cmd
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="Model", Name="Commande")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Commande : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Créez un nouvel objet Commande.
        /// </summary>
        /// <param name="id_cmd">Valeur initiale de id_cmd.</param>
        /// <param name="id_pers">Valeur initiale de id_pers.</param>
        /// <param name="id_bien">Valeur initiale de id_bien.</param>
        /// <param name="quantite">Valeur initiale de quantite.</param>
        public static Commande CreateCommande(int id_cmd, int id_pers, int id_bien, int quantite)
        {
            Commande commande = new Commande();
            commande.id_cmd = id_cmd;
            commande.id_pers = id_pers;
            commande.id_bien = id_bien;
            commande.quantite = quantite;
            return commande;
        }
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété id_cmd dans le schéma.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int id_cmd
        {
            get
            {
                return this._id_cmd;
            }
            set
            {
                this.Onid_cmdChanging(value);
                this.ReportPropertyChanging("id_cmd");
                this._id_cmd = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("id_cmd");
                this.Onid_cmdChanged();
            }
        }
        private int _id_cmd;
        partial void Onid_cmdChanging(int value);
        partial void Onid_cmdChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété id_pers dans le schéma.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int id_pers
        {
            get
            {
                return this._id_pers;
            }
            set
            {
                this.Onid_persChanging(value);
                this.ReportPropertyChanging("id_pers");
                this._id_pers = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("id_pers");
                this.Onid_persChanged();
            }
        }
        private int _id_pers;
        partial void Onid_persChanging(int value);
        partial void Onid_persChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété id_bien dans le schéma.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int id_bien
        {
            get
            {
                return this._id_bien;
            }
            set
            {
                this.Onid_bienChanging(value);
                this.ReportPropertyChanging("id_bien");
                this._id_bien = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("id_bien");
                this.Onid_bienChanged();
            }
        }
        private int _id_bien;
        partial void Onid_bienChanging(int value);
        partial void Onid_bienChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété quantite dans le schéma.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int quantite
        {
            get
            {
                return this._quantite;
            }
            set
            {
                this.OnquantiteChanging(value);
                this.ReportPropertyChanging("quantite");
                this._quantite = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("quantite");
                this.OnquantiteChanged();
            }
        }
        private int _quantite;
        partial void OnquantiteChanging(int value);
        partial void OnquantiteChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété d_cre dans le schéma.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<global::System.DateTime> d_cre
        {
            get
            {
                return this._d_cre;
            }
            set
            {
                this.Ond_creChanging(value);
                this.ReportPropertyChanging("d_cre");
                this._d_cre = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("d_cre");
                this.Ond_creChanged();
            }
        }
        private global::System.Nullable<global::System.DateTime> _d_cre;
        partial void Ond_creChanging(global::System.Nullable<global::System.DateTime> value);
        partial void Ond_creChanged();
    }
    /// <summary>
    /// Il n'existe aucun commentaire pour Model.Pays dans le schéma.
    /// </summary>
    /// <KeyProperties>
    /// id_pays
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="Model", Name="Pays")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Pays : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Créez un nouvel objet Pays.
        /// </summary>
        /// <param name="id_pays">Valeur initiale de id_pays.</param>
        /// <param name="nom_pays">Valeur initiale de nom_pays.</param>
        public static Pays CreatePays(int id_pays, string nom_pays)
        {
            Pays pays = new Pays();
            pays.id_pays = id_pays;
            pays.nom_pays = nom_pays;
            return pays;
        }
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété id_pays dans le schéma.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int id_pays
        {
            get
            {
                return this._id_pays;
            }
            set
            {
                this.Onid_paysChanging(value);
                this.ReportPropertyChanging("id_pays");
                this._id_pays = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("id_pays");
                this.Onid_paysChanged();
            }
        }
        private int _id_pays;
        partial void Onid_paysChanging(int value);
        partial void Onid_paysChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété nom_pays dans le schéma.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string nom_pays
        {
            get
            {
                return this._nom_pays;
            }
            set
            {
                this.Onnom_paysChanging(value);
                this.ReportPropertyChanging("nom_pays");
                this._nom_pays = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("nom_pays");
                this.Onnom_paysChanged();
            }
        }
        private string _nom_pays;
        partial void Onnom_paysChanging(string value);
        partial void Onnom_paysChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété d_cre dans le schéma.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<global::System.DateTime> d_cre
        {
            get
            {
                return this._d_cre;
            }
            set
            {
                this.Ond_creChanging(value);
                this.ReportPropertyChanging("d_cre");
                this._d_cre = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("d_cre");
                this.Ond_creChanged();
            }
        }
        private global::System.Nullable<global::System.DateTime> _d_cre;
        partial void Ond_creChanging(global::System.Nullable<global::System.DateTime> value);
        partial void Ond_creChanged();
    }
    /// <summary>
    /// Il n'existe aucun commentaire pour Model.Personne dans le schéma.
    /// </summary>
    /// <KeyProperties>
    /// id_pers
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="Model", Name="Personne")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Personne : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Créez un nouvel objet Personne.
        /// </summary>
        /// <param name="id_pers">Valeur initiale de id_pers.</param>
        /// <param name="nom">Valeur initiale de nom.</param>
        public static Personne CreatePersonne(int id_pers, string nom)
        {
            Personne personne = new Personne();
            personne.id_pers = id_pers;
            personne.nom = nom;
            return personne;
        }
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété id_pers dans le schéma.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int id_pers
        {
            get
            {
                return this._id_pers;
            }
            set
            {
                this.Onid_persChanging(value);
                this.ReportPropertyChanging("id_pers");
                this._id_pers = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("id_pers");
                this.Onid_persChanged();
            }
        }
        private int _id_pers;
        partial void Onid_persChanging(int value);
        partial void Onid_persChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété nom dans le schéma.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string nom
        {
            get
            {
                return this._nom;
            }
            set
            {
                this.OnnomChanging(value);
                this.ReportPropertyChanging("nom");
                this._nom = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("nom");
                this.OnnomChanged();
            }
        }
        private string _nom;
        partial void OnnomChanging(string value);
        partial void OnnomChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété age dans le schéma.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> age
        {
            get
            {
                return this._age;
            }
            set
            {
                this.OnageChanging(value);
                this.ReportPropertyChanging("age");
                this._age = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("age");
                this.OnageChanged();
            }
        }
        private global::System.Nullable<int> _age;
        partial void OnageChanging(global::System.Nullable<int> value);
        partial void OnageChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété d_cre dans le schéma.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<global::System.DateTime> d_cre
        {
            get
            {
                return this._d_cre;
            }
            set
            {
                this.Ond_creChanging(value);
                this.ReportPropertyChanging("d_cre");
                this._d_cre = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("d_cre");
                this.Ond_creChanged();
            }
        }
        private global::System.Nullable<global::System.DateTime> _d_cre;
        partial void Ond_creChanging(global::System.Nullable<global::System.DateTime> value);
        partial void Ond_creChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété prenom dans le schéma.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string prenom
        {
            get
            {
                return this._prenom;
            }
            set
            {
                this.OnprenomChanging(value);
                this.ReportPropertyChanging("prenom");
                this._prenom = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("prenom");
                this.OnprenomChanged();
            }
        }
        private string _prenom;
        partial void OnprenomChanging(string value);
        partial void OnprenomChanged();
    }
    /// <summary>
    /// Il n'existe aucun commentaire pour Model.sysdiagrams dans le schéma.
    /// </summary>
    /// <KeyProperties>
    /// diagram_id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="Model", Name="sysdiagrams")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class sysdiagrams : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Créez un nouvel objet sysdiagrams.
        /// </summary>
        /// <param name="name">Valeur initiale de name.</param>
        /// <param name="principal_id">Valeur initiale de principal_id.</param>
        /// <param name="diagram_id">Valeur initiale de diagram_id.</param>
        public static sysdiagrams Createsysdiagrams(string name, int principal_id, int diagram_id)
        {
            sysdiagrams sysdiagrams = new sysdiagrams();
            sysdiagrams.name = name;
            sysdiagrams.principal_id = principal_id;
            sysdiagrams.diagram_id = diagram_id;
            return sysdiagrams;
        }
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété name dans le schéma.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string name
        {
            get
            {
                return this._name;
            }
            set
            {
                this.OnnameChanging(value);
                this.ReportPropertyChanging("name");
                this._name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("name");
                this.OnnameChanged();
            }
        }
        private string _name;
        partial void OnnameChanging(string value);
        partial void OnnameChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété principal_id dans le schéma.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int principal_id
        {
            get
            {
                return this._principal_id;
            }
            set
            {
                this.Onprincipal_idChanging(value);
                this.ReportPropertyChanging("principal_id");
                this._principal_id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("principal_id");
                this.Onprincipal_idChanged();
            }
        }
        private int _principal_id;
        partial void Onprincipal_idChanging(int value);
        partial void Onprincipal_idChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété diagram_id dans le schéma.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int diagram_id
        {
            get
            {
                return this._diagram_id;
            }
            set
            {
                this.Ondiagram_idChanging(value);
                this.ReportPropertyChanging("diagram_id");
                this._diagram_id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("diagram_id");
                this.Ondiagram_idChanged();
            }
        }
        private int _diagram_id;
        partial void Ondiagram_idChanging(int value);
        partial void Ondiagram_idChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété version dans le schéma.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> version
        {
            get
            {
                return this._version;
            }
            set
            {
                this.OnversionChanging(value);
                this.ReportPropertyChanging("version");
                this._version = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("version");
                this.OnversionChanged();
            }
        }
        private global::System.Nullable<int> _version;
        partial void OnversionChanging(global::System.Nullable<int> value);
        partial void OnversionChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété definition dans le schéma.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] definition
        {
            get
            {
                return global::System.Data.Objects.DataClasses.StructuralObject.GetValidValue(this._definition);
            }
            set
            {
                this.OndefinitionChanging(value);
                this.ReportPropertyChanging("definition");
                this._definition = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("definition");
                this.OndefinitionChanged();
            }
        }
        private byte[] _definition;
        partial void OndefinitionChanging(byte[] value);
        partial void OndefinitionChanged();
    }
}
